// <auto-generated />
namespace BanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WebBanHangOnline26 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebBanHangOnline26));
        
        string IMigrationMetadata.Id
        {
            get { return "202405040946169_WebBanHangOnline26"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
