// <auto-generated />
namespace BanHangOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class WebBanHangOnline12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebBanHangOnline12));
        
        string IMigrationMetadata.Id
        {
            get { return "202403050443154_WebBanHangOnline12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
